# Generated by Django 5.0.2 on 2024-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='schedule',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
    ]
