# Generated by Django 5.0.2 on 2024-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_name', models.CharField(max_length=50)),
            ],
        ),
    ]
