# Generated by Django 5.0.2 on 2024-02-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_busbooking_schedule_busbooking_set_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
    ]
