# Generated by Django 5.0.2 on 2024-02-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_busbooking_bus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='set_number',
            new_name='seat_number',
        ),
    ]
