# Generated by Django 5.0.2 on 2024-02-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_rename_set_number_busbooking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
